server:
  port: 8085
spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Saurabh-Jayaswal/Microservices-Hotel_Rating
          clone-on-start: true